### ISSUE TITLE
cssBoxProp, cssDimensionProp missing from scssMixinParams

### ISSUE THREAD

**Issue by Zeit-Werk** [cakebaker/scss-syntax.vim#65]
As you can see in the following screenshot, `margin` and `width` are not properly highlighted.
![csspropsmissingbefore](https://cloud.githubusercontent.com/assets/15860486/14229983/d44e9d0e-f946-11e5-8d0a-e4f778c18d6c.jpg)

After adding `cssBoxProp` and `cssDimensionProp` to `contains` in `scssMixinParams`, both are highlighted again. (Granted, not as visible as I would like with this colorscheme)
![csspropsmissingafter](https://cloud.githubusercontent.com/assets/15860486/14229990/ff6f768e-f946-11e5-9be3-766e156f6c7b.jpg)

Maybe unrelated, `padding` is not recognized as a `cssBoxProp` for some reason, I'm still trying to figure out why.

**Comment by cakebaker** [comment]
Fixed in https://github.com/cakebaker/scss-syntax.vim/commit/bf65d5d7d2a9314e19ec60d648f012b0e896ebee. Thanks for reporting.

The problem with <code>padding</code> is that it's ambiguous, it can be either a <code>cssBoxProp</code> or a <code>cssUIAttr</code>, and both types are allowed as <code>scssMixinParams</code>...
